# Generated by Django 5.1.5 on 2025-02-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spz', models.CharField(max_length=10, unique=True, verbose_name='SPZ')),
                ('znacka', models.CharField(max_length=50, verbose_name='Značka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('rok_vyroby', models.IntegerField(verbose_name='Rok výroby')),
                ('stk', models.DateField(verbose_name='Platnost STK')),
                ('dalnicni_znamka', models.DateField(verbose_name='Platnost dálniční známky')),
                ('vymena_oleje', models.DateField(verbose_name='Datum poslední výměny oleje')),
                ('km_vymena_oleje', models.IntegerField(verbose_name='Kilometry při výměně oleje')),
            ],
        ),
        migrations.CreateModel(
            name='ServisniUkon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum servisu')),
                ('popis', models.TextField(verbose_name='Popis servisního úkonu')),
                ('km', models.IntegerField(verbose_name='Kilometry při servisu')),
                ('vozidlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servisni_ukony', to='viewer.vehicle')),
            ],
        ),
    ]
