# Generated by Django 5.1.5 on 2025-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='km_vymena_oleje',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vymena_oleje',
        ),
        migrations.AddField(
            model_name='servisniukon',
            name='typ',
            field=models.CharField(choices=[('vymena_oleje', 'Výměna oleje'), ('oprava', 'Oprava'), ('vymena', 'Výměna dílu'), ('jine', 'Jiný servisní úkon')], default='jine', max_length=20, verbose_name='Typ úkonu'),
        ),
        migrations.AlterField(
            model_name='servisniukon',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='Popis servisního úkonu'),
        ),
    ]
