# Generated by Django 5.1.5 on 2025-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_vehicle_dalnicni_znamka'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pojistka',
            field=models.DateField(blank=True, null=True, verbose_name='Platnost povinného ručení'),
        ),
    ]
